
-- BULK IMPORT SCRIPT
-- Replace '02715b73-acf3-4252-a029-ce8dd7e1ab8e' with your actual Supabase User ID (UUID)
-- You can find this in Authentication > Users

INSERT INTO materials (
  user_id, title, description, material_type, 
  course, specialization, subject, university, language, 
  uploaded_by, file_url, status, created_at
) VALUES 
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'Webtech Chapter 1 Network Basics Question Bank', 
    'Chapter 1 of intro to webtech question bank solution', 
    'Question Paper', 
    'B.Tech', 
    'AI and Data Science', 
    'Introduction To Webtech', 
    'JG University', 
    'English', 
    'Chirag Mahajan', 
    'https://drive.google.com/file/d/1p8ZT1NszwraGUxFK93xlnL-SOcKQCjJV/view?usp=sharing', 
    'pending', 
    '2026-02-10'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'Mathematics-I Paper Solution', 
    'Fully Paper Solution of Mathematics-I Monark Uni', 
    'Question Paper', 
    'BE', 
    'All', 
    'Mathematics-I', 
    'Monark University', 
    'English', 
    'E-Material Team', 
    'https://drive.google.com/file/d/1reFlK9KCuqFxufiokcq7UYK3rkCLB1Tk/view?usp=drive_link', 
    'pending', 
    '2025-12-11'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'PTC University Paper', 
    'PTC University Exam Paper Sem-3 Monark Uni Dec/25', 
    'Question Paper', 
    'BE', 
    'All', 
    'PTC', 
    'Monark University', 
    'English', 
    'E-Material Team', 
    'https://drive.google.com/file/d/1-uOfBYp_Ok7p65N1e54GtA4GhaoGcT3f/view?usp=sharing', 
    'pending', 
    '2025-12-11'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'Probability & Statistics University Paper', 
    'Probability & Statistics University Exam Paper Sem-3 Monark Uni Dec/25', 
    'Question Paper', 
    'BE', 
    'All', 
    'Probability & Statistics', 
    'Monark University', 
    'English', 
    'E-Material Team', 
    'https://drive.google.com/file/d/1BCtJoAnnr9864kcKIYz-gY1S4svJXfYl/view?usp=sharing', 
    'pending', 
    '2025-12-11'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'FDE University Paper', 
    'FDE University Exam Paper Sem-3 Monark Uni Dec/25', 
    'Question Paper', 
    'BE', 
    'All', 
    'FDE', 
    'Monark University', 
    'English', 
    'E-Material Team', 
    'https://drive.google.com/file/d/1Xx28qiqI7U-p_kmkBlTptXa7rG15jbIt/view?usp=sharing', 
    'pending', 
    '2025-12-11'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'DBMS University Paper', 
    'DBMS University Exam Paper Sem-3 Monark Uni Dec/25', 
    'Question Paper', 
    'BE', 
    'All', 
    'DBMS', 
    'Monark University', 
    'English', 
    'E-Material Team', 
    'https://drive.google.com/file/d/1OPUWd9bWTBqP3uLCDIg60TRaSOP2Lb9Y/view?usp=sharing', 
    'pending', 
    '2025-12-11'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'ICSD University Paper', 
    'ICSD University Exam Paper Sem-3 Monark Uni Dec/25', 
    'Question Paper', 
    'BE', 
    'All', 
    'ICSD', 
    'Monark University', 
    'English', 
    'E-Material Team', 
    'https://drive.google.com/file/d/1ytMV8R1cwtgLjGTEyhp6y2rviQgvLS5o/view?usp=sharing', 
    'pending', 
    '2025-12-11'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'Data Structure University Paper', 
    'Data Structure University Exam Paper Sem-3 Monark Uni Dec/25', 
    'Question Paper', 
    'BE', 
    'All', 
    'Data Structure', 
    'Monark University', 
    'English', 
    'E-Material Team', 
    'https://drive.google.com/file/d/1hNmy73R6TrlzApzIs77c7WL483rJGkDy/view?usp=sharing', 
    'pending', 
    '2025-12-11'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'Indian Constitution University Paper', 
    'Indian Constitution University Exam Paper Sem-3 Monark Uni Dec/25', 
    'Question Paper', 
    'BE', 
    'All', 
    'Indian Constitution', 
    'Monark University', 
    'English', 
    'E-Material Team', 
    'https://drive.google.com/file/d/1Yjkr6C6L52-HvZgPOVewcBDRSs7ZePp9/view?usp=sharing', 
    'pending', 
    '2025-12-11'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'Indian Constitution FAQ Answer Document', 
    'Indian Constitution ALL FAQS With Answers', 
    'Important Questions', 
    'BE', 
    'All', 
    'Indian Constitution', 
    'Monark University', 
    'English', 
    'Jiya', 
    'https://drive.google.com/file/d/1USRbCLJb9zjQpHwOdqxcf6ZEaPSj-kJN/view?usp=sharing', 
    'pending', 
    '2025-11-30'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'DBMS FAQ Handwritten Answer', 
    'DBMS ALL FAQS With Handwritten Answers', 
    'Important Questions', 
    'BE', 
    'Computer', 
    'DBMS', 
    'Monark University', 
    'English', 
    'Jiya', 
    'https://drive.google.com/file/d/13rZnIkC8KLlsbwV2t4J5PIrfLVvG4ZUf/view?usp=sharing', 
    'pending', 
    '2025-11-27'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'DBMS FAQ Answer Document', 
    'DBMS ALL FAQS With Answers', 
    'Important Questions', 
    'BE', 
    'All', 
    'DBMS', 
    'Monark University', 
    'English', 
    'Jiya', 
    'https://drive.google.com/file/d/1YJ_Af0_ofHbNgtNsUdGOIcSNEepJbKl5/view?usp=sharing', 
    'pending', 
    '2025-11-27'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'DBMS FAQs for University Exam', 
    'DBMS ALL FAQS', 
    'Important Questions', 
    'BE', 
    'All', 
    'DBMS', 
    'Monark University', 
    'English', 
    'Poojan Desai', 
    'https://drive.google.com/file/d/10XW-Hx74ba9umh9svpJaGmWl908KTgUr/view?usp=sharing', 
    'pending', 
    '2025-11-27'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'FDE FAQ Answer Document', 
    'FDE ALL FAQS With Answers', 
    'Important Questions', 
    'BE', 
    'All', 
    'FDE', 
    'Monark University', 
    'English', 
    'Jiya', 
    'https://drive.google.com/file/d/10BKl81M0gQq5dnIbTgM7iylHAwiZ7d_O/view?usp=sharing', 
    'pending', 
    '2025-11-26'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'DS FAQ Handwritten Answer', 
    'Data Structure ALL FAQS With Handwritten Answers', 
    'Important Questions', 
    'BE', 
    'Computer', 
    'DS', 
    'Monark University', 
    'English', 
    'Jiya', 
    'https://drive.google.com/file/d/1I3Oqjj1gdupA50kK_cP7Uv61mf52UVMv/view?usp=sharing', 
    'pending', 
    '2025-11-22'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'DS FAQ Answer Document', 
    'Data Structure ALL FAQS With Answers', 
    'Important Questions', 
    'BE', 
    'All', 
    'DS', 
    'Monark University', 
    'English', 
    'Jiya', 
    'https://drive.google.com/file/d/1r4ug4RCxeug_xetQiYLrg7CkkB6DL40Q/view?usp=sharing', 
    'pending', 
    '2025-11-22'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'DS FAQs for University Exam', 
    'DS ALL FAQS', 
    'Important Questions', 
    'BE', 
    'All', 
    'Data Structure', 
    'Monark University', 
    'English', 
    'Monark University', 
    'https://drive.google.com/file/d/1odeMjia0_FmzAotx0vCAKrYpk74opvGl/view?usp=sharing', 
    'pending', 
    '2025-11-22'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'PTC FAQ Handwritten Answer', 
    'PTC ALL FAQS With Handwritten Answers', 
    'Important Questions', 
    'BE', 
    'Computer', 
    'PTC', 
    'Monark University', 
    'English', 
    'Jiya', 
    'https://drive.google.com/file/d/1XVynxAsqWKkj8VZ6fferBQLtd-xgc7yZ/view?usp=sharing', 
    'pending', 
    '2025-11-22'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'PTC FAQ Answer Document', 
    'PTC ALL FAQS With Answers', 
    'Important Questions', 
    'BE', 
    'All', 
    'PTC', 
    'Monark University', 
    'English', 
    'Jiya', 
    'https://drive.google.com/file/d/1btviYeRx5oWNOTNai8Ciz-SuVoepUygO/view?usp=sharing', 
    'pending', 
    '2025-11-22'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'PTC FAQs for University Exam', 
    'PTC ALL FAQS', 
    'Important Questions', 
    'BE', 
    'All', 
    'PTC', 
    'Monark University', 
    'English', 
    'Poojan Desai', 
    'https://drive.google.com/file/d/1VEo5MITMdoR5IFFexrmOiNBgqskYr-ER/view?usp=sharing', 
    'pending', 
    '2025-11-22'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'DS All Assignment (MU)', 
    'DS ALL CH Assignment With Answers', 
    'Assignment', 
    'BE', 
    'Computer', 
    'Data Structure', 
    'Monark University', 
    'English', 
    'E-Material Team', 
    'https://drive.google.com/file/d/1FL5J4Gogob8e8HDAlzDypkXepjK9ki7L/view?usp=sharing', 
    'pending', 
    '2025-09-13'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'DS Ch-1,2 Assignment (MU)', 
    'DS Ch-1,2 Assignment With Answers', 
    'Assignment', 
    'BE', 
    'Computer', 
    'Data Structure', 
    'Monark University', 
    'English', 
    'PRAJAPATI KUSH', 
    'https://drive.google.com/file/d/1hzBO1pvDG5KdwGVGmLH1bJqvutXn9NTS/view?usp=sharing', 
    'pending', 
    '2025-09-08'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'FDE All Assignment (MU)', 
    'FDE All Assignment With Answers', 
    'Assignment', 
    'BE', 
    'Computer', 
    'FDE', 
    'Monark University', 
    'English', 
    'E-Material Team', 
    'https://drive.google.com/file/d/1QUBpd1p0gsN1sQB4jTCSbM_0BZ4BEViQ/view?usp=sharing', 
    'pending', 
    '2025-09-03'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'DBMS All Assignment (MU)', 
    'DBMS All Assignment With Answers', 
    'Assignment', 
    'BE', 
    'Computer', 
    'DBMS', 
    'Monark University', 
    'English', 
    'E-Material Team', 
    'https://drive.google.com/file/d/1U38YMnCGqyU72KYpJBl0sJ-SkTagUwX0/view?usp=sharing', 
    'pending', 
    '2025-08-31'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'CN Lab Manual with answer', 
    'CN Lab Manual With Answers', 
    'Lab Manual', 
    'Diploma', 
    'Computer', 
    'Computer Network', 
    'Gujarat Technological University', 
    'English', 
    'Amanat Malek', 
    'https://drive.google.com/file/d/1Ho6bDx8whjleh4Mc14kafk0nF8pGNl61/view?usp=sharing', 
    'pending', 
    '2025-08-23'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'DBMS Full Syllabus Notes', 
    'DBMS Full syllabus Notes for degree students', 
    'Notes', 
    'Degree', 
    'Computer', 
    'DBMS', 
    'Gujarat Technological University', 
    'English', 
    'E-Material', 
    'https://drive.google.com/file/d/1Q7Ehqx_pJbD9txWfzdG4ELFAgw90YCjW/view?usp=sharing', 
    'pending', 
    '2025-08-05'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'Introduction to NO SQL Lab Manual With Answer', 
    'Introduction to NO SQL (4360704) Lab manual With Answer', 
    'Lab Manual', 
    'Diploma', 
    'Computer', 
    'Introduction to NO SQL', 
    'Gujarat Technological University', 
    'English', 
    'E-Material', 
    'https://drive.google.com/file/d/1rwYQ-LJg5okwt99r4opeeKFruCJ45suT/view?usp=sharing', 
    'pending', 
    '2025-04-29'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'Basic of Information Security Lab Manual With Answer', 
    'Basic of Information Security (4360702) Lab manual With Answer', 
    'Lab Manual', 
    'Diploma', 
    'Computer', 
    'Basic of Information Security', 
    'Gujarat Technological University', 
    'English', 
    'E-Material', 
    'https://drive.google.com/file/d/1BpI_7EDd2G9YHKcdh2NY6gQvO1gmqSus/view?usp=sharing', 
    'pending', 
    '2025-04-26'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'DDCET Paper Solution 2024', 
    'DDCET Paper Solution 2024 last year', 
    'Question Paper', 
    'Diploma', 
    'Computer', 
    'DDCET', 
    'Gujarat Technological University', 
    'English', 
    'E-Material', 
    'https://drive.google.com/file/d/1BNoWnLNxhsmxMxvAukiH9Stp53vNL7gA/view?usp=sharing', 
    'pending', 
    '2025-04-09'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'Cloud Computing Lab Manual With Answer', 
    'Cloud Computing (4360709) Lab manual With Answer', 
    'Lab Manual', 
    'Diploma', 
    'Computer', 
    'Cloud Computing', 
    'Gujarat Technological University', 
    'English', 
    'E-Material', 
    'https://drive.google.com/file/d/1b-zNFl4gKiPFcEfJPh5ooyeQzoaSPti8/view?usp=sharing', 
    'pending', 
    '2025-03-27'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'Computer Maintenance and Troubleshooting Lab Manual With Answer', 
    'Computer Maintenance and Troubleshooting (4360701) Lab manual With Answer', 
    'Lab Manual', 
    'Diploma', 
    'Computer', 
    'Computer Maintenance and Troubleshooting', 
    'Gujarat Technological University', 
    'English', 
    'E-Material', 
    'https://drive.google.com/file/d/1pxTAiHv3I4QRLEW5nl_ZA7e2QFJX2vdW/view?usp=sharing', 
    'pending', 
    '2025-03-25'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'Computer Maintenance and Troubleshooting Assignment 1 to 3', 
    'Sem 6 Computer Maintenance and Troubleshooting Unit 1 to 3 Handwritten Assignment', 
    'Assignment', 
    'Diploma', 
    'Computer', 
    'Computer Maintenance and Troubleshooting', 
    'Gujarat Technological University', 
    'English', 
    'E-Material', 
    'https://drive.google.com/file/d/1hKndL-Iy10WPeC8CAzVCFqTakNK82EO2/view?usp=sharing', 
    'pending', 
    '2025-03-23'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'Fundamentals Of IOT All Assignment', 
    'Sem 6 Fundamentals Of IOT All Units Handwritten Assignment', 
    'Assignment', 
    'Diploma', 
    'Computer', 
    'Fundamentals Of IOT', 
    'Gujarat Technological University', 
    'English', 
    'E-Material', 
    'https://drive.google.com/file/d/1sjcf0NtmYpk5tCvVnU-TK333BGN2og5j/view?usp=sharing', 
    'pending', 
    '2025-03-21'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'BIS All Assignment', 
    'Sem 6 BIS All Units Handwritten Assignment', 
    'Assignment', 
    'Diploma', 
    'Computer', 
    'Basic of Information Security', 
    'Gujarat Technological University', 
    'English', 
    'E-Material', 
    'https://drive.google.com/file/d/11BTsHBatAk7--1zp9c0dOWm7cWDmdWsR/view?usp=sharing', 
    'pending', 
    '2025-03-21'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'Cloud Computing All Assignments', 
    'Sem 6 Cloud Computing All Assignments', 
    'Assignment', 
    'Diploma', 
    'Computer', 
    'Cloud Computing', 
    'Gujarat Technological University', 
    'English', 
    'E-Material', 
    'https://drive.google.com/file/d/1Yvn7xUCtBel16bqbiql2xoRunkybj-gw/view?usp=sharing', 
    'pending', 
    '2025-01-28'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'Cyber Security and Digital Forensics Lab Manual', 
    'Cyber Security and Digital Forensics Lab manual from GTU', 
    'Lab Manual', 
    'Diploma', 
    'IT', 
    'Cyber Security and Digital Forensics', 
    'GTU', 
    'English', 
    'E-Material', 
    'https://drive.google.com/file/d/1dMdWk4uY1dZHZyjaoCQy2QY5tU1rzNZ0/view?usp=sharing', 
    'pending', 
    '2025-01-22'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'Cloud and Data Center Technologies Lab Manual', 
    'Cloud and Data Center Technologies Lab manual from GTU', 
    'Lab Manual', 
    'Diploma', 
    'IT', 
    'Cloud and Data Center Technologies', 
    'GTU', 
    'English', 
    'E-Material', 
    'https://drive.google.com/file/d/14b5xQvPxI4auXto9COBAUK_X4iBJ0_Ok/view?usp=sharing', 
    'pending', 
    '2025-01-22'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'Fundamentals of IoT Lab Manual With Answer', 
    'Fundamentals of IoT Lab manual With Answer', 
    'Lab Manual', 
    'Diploma', 
    'Computer', 
    'Fundamentals of IoT', 
    'Gujarat Technological University', 
    'English', 
    'E-Material', 
    'https://drive.google.com/file/d/1dgqb3qSgRcCiWN14fHKl4HXkfGve4M58/view?usp=sharing', 
    'pending', 
    '2025-01-17'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'Fundamentals of IoT Lab Manual', 
    'Fundamentals of IoT Lab manual from GTU', 
    'Lab Manual', 
    'Diploma', 
    'Computer', 
    'Fundamentals of IoT', 
    'GTU', 
    'English', 
    'E-Material', 
    'https://drive.google.com/file/d/128C3bFcVZWhJ3NRapSzqXy72q61YNpzJ/view?usp=sharing', 
    'pending', 
    '2025-01-17'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'Cloud Computing Lab Manual', 
    'Cloud Computing Lab manual from GTU', 
    'Lab Manual', 
    'Diploma', 
    'Computer', 
    'Cloud Computing', 
    'GTU', 
    'English', 
    'E-Material', 
    'https://drive.google.com/file/d/1570ZUss8mXpXtFrkEjavciMq2XufA9Eq/view?usp=sharing', 
    'pending', 
    '2025-01-17'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'INS Lab Manual', 
    'INS Lab manual from GTU', 
    'Lab Manual', 
    'Diploma', 
    'Computer', 
    'Introduction to NO SQL', 
    'GTU', 
    'English', 
    'E-Material', 
    'https://drive.google.com/file/d/1TDFaBeyfuhsnnKqS_TvWgH2hf9fcp5r7/view?usp=sharing', 
    'pending', 
    '2025-01-17'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'BIS Lab Manual', 
    'BIS Lab manual from GTU', 
    'Lab Manual', 
    'Diploma', 
    'Computer', 
    'Basics of Information Security', 
    'GTU', 
    'English', 
    'E-Material', 
    'https://drive.google.com/file/d/1yXsUanjxCZxJYh2FAeQj-tuvxGVlhYHM/view?usp=sharing', 
    'pending', 
    '2025-01-17'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'CMTS Lab Manual', 
    'CMTS Lab manual from GTU', 
    'Lab Manual', 
    'Diploma', 
    'Computer', 
    'Computer Maintenance and Troubleshooting', 
    'GTU', 
    'English', 
    'E-Material', 
    'https://drive.google.com/file/d/1-fyoTwiUWzYx0_GUGqIUAG4axLX26QSo/view?usp=sharing', 
    'pending', 
    '2025-01-17'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'Computer Networking Lab Manual', 
    'Computer Networking Lab manual from GTU', 
    'Lab Manual', 
    'Diploma', 
    'Computer', 
    'Computer Networking', 
    'GTU', 
    'English', 
    'E-Material', 
    'https://drive.google.com/file/d/1-eo4jppkQqhRyNVXv6b_uirNGwokhzPg/view?usp=sharing', 
    'pending', 
    '2025-01-17'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'JAVA Notes', 
    'IMP Notes for JAVA by Krish Wagh', 
    'Notes', 
    'Computer Science', 
    '-', 
    'Coding', 
    'Gujarat Technological University', 
    'English', 
    'Krish Wagh', 
    'https://drive.google.com/file/d/1s8IcbTvbe_WkA5LWcF_SsHu-IbReVLa0/view?usp=sharing', 
    'pending', 
    '2025-01-16'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'PHP Notes', 
    'IMP Notes for PHP by Devji', 
    'Notes', 
    'Computer Science', 
    '-', 
    'Coding', 
    'Gujarat Technological University', 
    'English', 
    'Devji', 
    'https://drive.google.com/file/d/1Jo7EYiqKTOP2t4Y3Q2mgsY8EsiA6-Ky2/view?usp=sharing', 
    'pending', 
    '2025-01-06'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'Javascript Notes', 
    'IMP Notes for Javascript by Devji', 
    'Notes', 
    'Computer Science', 
    '-', 
    'Coding', 
    'Gujarat Technological University', 
    'English', 
    'Devji', 
    'https://drive.google.com/file/d/13kV17UnY7hbK20kP2Drh6s60xOUZzwbr/view?usp=sharing', 
    'pending', 
    '2025-01-01'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'CSS Notes', 
    'IMP Notes for CSS by Devji', 
    'Notes', 
    'Computer Science', 
    '-', 
    'Coding', 
    'Gujarat Technological University', 
    'English', 
    'Devji', 
    'https://drive.google.com/file/d/1uqnpKmwrADgmJYXyL8EWJ2BayLelJ2ZW/view?usp=sharing', 
    'pending', 
    '2025-01-01'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'HTML Notes', 
    'IMP Notes for HTML by Devji', 
    'Notes', 
    'Computer Science', 
    '-', 
    'Coding', 
    'Gujarat Technological University', 
    'English', 
    'Devji', 
    'https://drive.google.com/file/d/1Uey5DXx5PiwLI0mysIgvd81uokk93Wzg/view?usp=sharing', 
    'pending', 
    '2025-01-01'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'C Programming Notes', 
    'IMP Notes for C Programming by Devji', 
    'Notes', 
    'Computer Science', 
    '-', 
    'Coding', 
    'Gujarat Technological University', 
    'English', 
    'Devji', 
    'https://drive.google.com/drive/folders/1RB5t3Xt8dtoRdBMubBQQTN-fISNv687b', 
    'pending', 
    '2024-12-30'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'Quantum Computing Notes', 
    'IMP Notes for Quantum Computing by Devji', 
    'Notes', 
    'Computer Science', 
    '-', 
    'Coding', 
    'Gujarat Technological University', 
    'English', 
    'Devji', 
    'https://drive.google.com/file/d/1t0qGOTV2_1O4oM7UJ3JLrYTJyO71UmOG/view?usp=sharing', 
    'pending', 
    '2024-12-30'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'Python Notes', 
    'IMP Notes for Python by Devji', 
    'Notes', 
    'Computer Science', 
    '-', 
    'Coding', 
    'Gujarat Technological University', 
    'English', 
    'Devji', 
    'https://drive.google.com/file/d/14Ru7qUuZEbNnpBX-N8lulWLxs9iyTJfd/view?usp=sharing', 
    'pending', 
    '2024-12-30'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'Java Notes', 
    'IMP Notes for Java by Devji', 
    'Notes', 
    'Computer Science', 
    '-', 
    'Coding', 
    'Gujarat Technological University', 
    'English', 
    'Devji', 
    'https://drive.google.com/file/d/1TnLXta0tC2WNkkItiRaYnsHpmmlrPw8r/view?usp=sharing', 
    'pending', 
    '2024-12-28'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'C++ Notes', 
    'IMP Notes for C++ by Devji', 
    'Notes', 
    'Computer Science', 
    '-', 
    'Coding', 
    'Gujarat Technological University', 
    'English', 
    'Devji', 
    'https://drive.google.com/file/d/1BUmgJmU4Q5oRzOmcnXUHFAzGkheOzxpl/view?usp=sharing', 
    'pending', 
    '2024-12-30'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'Most IMP questions for ACN', 
    'Most imp questions for ACN subject', 
    'Important Questions', 
    'Diploma', 
    'Computer', 
    'Advance Computer Network', 
    'Gujarat Technological University', 
    'English', 
    'Chirag', 
    'https://drive.google.com/file/d/1vLUEbyeu6x4Vir-5sLoYvg0vs3UIy7sk/view?usp=sharing', 
    'pending', 
    '2024-11-23'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'COA IMP GTU PAPER', 
    'COA GTU IMP Question and Answers', 
    'Question Paper', 
    'Diploma', 
    'Computer', 
    'Computer Organisations and Architecture', 
    'GTU', 
    'English', 
    'Chirag', 
    'https://drive.google.com/file/d/1kiyTb0j0IAV8SgE4bxEHayouH4yAYkxl/view?usp=sharing', 
    'pending', 
    '2024-11-12'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'AOOP GTU PAPER (S-2024)', 
    'AOOP GTU PAPER Summer 2024', 
    'Question Paper', 
    'Diploma', 
    'Computer', 
    'Advance Object Oriented Programming', 
    'GTU', 
    'English', 
    'Harshil', 
    'https://drive.google.com/file/d/1MBLNYJmDPajiiPcYIf3pu0rspM15HaxN/view?usp=drive_link', 
    'pending', 
    '2024-11-12'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'CN GTU PAPER (S-2024)', 
    'Computer Network GTU PAPER Summer 2024', 
    'Question Paper', 
    'Diploma', 
    'Computer', 
    'Computer Network', 
    'GTU', 
    'English', 
    'Harshil', 
    'https://drive.google.com/file/d/1nR3kmbq5dagWzjIeF5iAt19HYzvI7ke6/view?usp=drive_link', 
    'pending', 
    '2024-11-12'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'ISE GTU PAPER (S-2024)', 
    'ISE GTU PAPER Summer 2024', 
    'Question Paper', 
    'Diploma', 
    'Computer', 
    'Introduction to Software Engineering', 
    'GTU', 
    'English', 
    'Harshil', 
    'https://drive.google.com/file/d/1l_ofYxNyhyIMvKK7WBAoBL2socvDEcfX/view?usp=drive_link', 
    'pending', 
    '2024-11-12'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'IWD GTU PAPER (S-2024)', 
    'IWD GTU PAPER Summer 2024', 
    'Question Paper', 
    'Diploma', 
    'Computer', 
    'Introduction to Web Development', 
    'GTU', 
    'English', 
    'Harshil', 
    'https://drive.google.com/file/d/1tZLRotMk1NtRAl6kzjJjUsao3MA5oqJ4/view?usp=drive_link', 
    'pending', 
    '2024-11-12'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'DSA GTU PAPER (S-2024)', 
    'DSA GTU PAPER Summer 2024', 
    'Question Paper', 
    'Diploma', 
    'Computer', 
    'Data Structure and Algorithms', 
    'GTU', 
    'English', 
    'Harshil', 
    'https://drive.google.com/file/d/1jXXBleSP4f1xa-TQlCxDajUFk-pIBCZW/view?usp=drive_link', 
    'pending', 
    '2024-11-12'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'RDBMS GTU PAPER (S-2024)', 
    'RDBMS GTU PAPER Summer 2024', 
    'Question Paper', 
    'Diploma', 
    'Computer', 
    'Relational Database Management System', 
    'GTU', 
    'English', 
    'Harshil', 
    'https://drive.google.com/file/d/1_nt9mhqZGlllGtnzjBeyZs9FlhU0B5yK/view?usp=sharing', 
    'pending', 
    '2024-11-12'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'BOS GTU PAPER (S-2024)', 
    'BOS GTU PAPER Summer 2024', 
    'Question Paper', 
    'Diploma', 
    'Computer', 
    'Basics of Operating System', 
    'GTU', 
    'English', 
    'Harshil', 
    'https://drive.google.com/file/d/1A-xSsS0LIpOgbSAbX2gMdeRp--xoWees/view?usp=drive_link', 
    'pending', 
    '2024-11-12'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'BDE GTU PAPER (S-2024)', 
    'BDE GTU PAPER Summer 2024', 
    'Question Paper', 
    'Diploma', 
    'Computer', 
    'Basics of Digital Electronics', 
    'GTU', 
    'English', 
    'Harshil', 
    'https://drive.google.com/file/d/1VGOGCems8h_NxCH5Tc9ylnoC2iSxFXCk/view?usp=sharing', 
    'pending', 
    '2024-11-12'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'Engineering Mathematics GTU PAPER (S-2024)', 
    'Engineering Mathematics GTU PAPER Summer 2024', 
    'Question Paper', 
    'Diploma', 
    'Computer', 
    'Engineering Mathematics', 
    'GTU', 
    'English', 
    'Harshil', 
    'https://drive.google.com/file/d/1HjjbQ7cdycKJGJc8O7_LjdczrA5BiL_l/view?usp=drive_link', 
    'pending', 
    '2024-11-12'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'COA Lab Manual With Answer', 
    'COA Lab Manual With Answer', 
    'Lab Manual', 
    'Diploma', 
    'Computer', 
    'COA', 
    'GTU', 
    'English', 
    'Harshil', 
    'https://drive.google.com/file/d/1QE-72N-liipTPwjAJB8SeJFBUEKoRA1C/view?usp=sharing', 
    'pending', 
    '2024-10-21'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'ACN Lab Manual With Answer', 
    'ACN Lab Manual With Answer', 
    'Lab Manual', 
    'Diploma', 
    'Computer', 
    'ACN', 
    'GTU', 
    'English', 
    'Harshil', 
    'https://drive.google.com/file/d/1SE4WCWpxw7EkHJyiL5lMqwu_4uiN9B3-/view?usp=sharing', 
    'pending', 
    '2024-10-20'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'IML Lab Manual With Answer', 
    'IML Lab Manual With Answer', 
    'Lab Manual', 
    'Diploma', 
    'Computer', 
    'IML', 
    'GTU', 
    'English', 
    'Mufiz', 
    'https://drive.google.com/file/d/11GDJkCDadCYT4DqrUERNbRIV1Iej5Ja7/view?usp=sharing', 
    'pending', 
    '2024-10-20'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'ACN Lab Manual (GTU)', 
    'ACN Lab manual from GTU', 
    'Lab Manual', 
    'Diploma', 
    'Computer', 
    'ACN', 
    'GTU', 
    'English', 
    'Harshil', 
    'https://drive.google.com/file/d/15edcY4wbBDCrpux6nU1XxuMcyecL_ydZ/view?usp=sharing', 
    'pending', 
    '2024-10-20'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'IML Lab Manual (GTU)', 
    'IML Lab manual from GTU', 
    'Lab Manual', 
    'Diploma', 
    'Computer', 
    'IML', 
    'GTU', 
    'English', 
    'Harshil', 
    'https://drive.google.com/file/d/1_95cVuImF1LGvW2iGXIKexpeJKIubtYS/view?usp=sharing', 
    'pending', 
    '2024-10-20'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'COA Lab Manual (GTU)', 
    'COA Lab manual from GTU', 
    'Lab Manual', 
    'Diploma', 
    'Computer', 
    'COA', 
    'GTU', 
    'English', 
    'Harshil', 
    'https://drive.google.com/file/d/1I7nBPVXtxq4HrT1do6NHlfYMX0eOmadr/view?usp=sharing', 
    'pending', 
    '2024-10-20'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'ACN Assignment All', 
    'Sem 5 ACN All Chapter Handwritten Assignment', 
    'Assignment', 
    'Diploma', 
    'Computer', 
    'ACN', 
    'Gujarat Technological University', 
    'English', 
    'Chirag', 
    'https://drive.google.com/file/d/1rt5sGDIBlEpQiPP9tE7-vXYCFlXcdFxk/view?usp=sharing', 
    'pending', 
    '2024-10-18'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'COA Assignment All', 
    'Sem 5 COA All Chapter Handwritten Assignment', 
    'Assignment', 
    'Diploma', 
    'Computer', 
    'COA', 
    'Gujarat Technological University', 
    'English', 
    'Chirag', 
    'https://drive.google.com/file/d/1kiyTb0j0IAV8SgE4bxEHayouH4yAYkxl/view?usp=sharing', 
    'pending', 
    '2024-10-15'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'Financial Accounting Assignment 2', 
    'Second handwritten assignment of financial accounting b.com 1st sem', 
    'Assignment', 
    'B.Com', 
    '-', 
    'Financial Accounting', 
    'Gujarat Technological University', 
    'Gujarati', 
    'Man Panchal', 
    'https://drive.google.com/file/d/1NGyFToJ-uzw2JS3k6TgztJ1g_wE16dyV/view?usp=sharing', 
    'pending', 
    '2024-10-11'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'Marketing Management Notes', 
    'Handwritten notes for marketing management b.com 1st sem', 
    'Notes', 
    'B.Com', 
    '-', 
    'Marketing Management', 
    'Gujarat Technological University', 
    'Gujarati', 
    'Man Panchal', 
    'https://drive.google.com/file/d/1ztyDv41R7I7Aa2T852TDig_mu2qvFjyy/view?usp=sharing', 
    'pending', 
    '2024-10-11'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'Economics Notes', 
    'Handwritten notes for b.com 1st sem economics', 
    'Notes', 
    'B.Com', 
    '-', 
    'Economics', 
    'Gujarat Technological University', 
    'Gujarati', 
    'Man Panchal', 
    'https://drive.google.com/file/d/1PvFWvnUe5GHDVsHhVtv_9RCdaAxQuSOS/view?usp=sharing', 
    'pending', 
    '2024-10-11'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'Indian Knowledge System Notes', 
    'Handwritten notes of IKS b.com 1st sem', 
    'Notes', 
    'B.Com', 
    '-', 
    'Indian Knowledge System', 
    'Gujarat Technological University', 
    'Gujarati', 
    'Man Panchal', 
    'https://drive.google.com/file/d/1MdYSmqPiGuoaef7mprZwc59YsW5eu3nA/view?usp=sharing', 
    'pending', 
    '2024-10-11'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'Financial Accounting Assignment 1', 
    'Handwritten assignment 1 of Financial Accounting b.com 1st sem', 
    'Assignment', 
    'B.Com', 
    '-', 
    'Financial Accounting', 
    'Gujarat Technological University', 
    'Gujarati', 
    'Man Panchal', 
    'https://drive.google.com/file/d/1HIeWnuF64M0ZeZ4vt4GrPh5cBYm_osnp/view?usp=sharing', 
    'pending', 
    '2024-10-11'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'IML Assignment All', 
    'Diploma Computer Sem 5 IML All Chapter Handwritten Assignment', 
    'Assignment', 
    'Diploma', 
    'Computer', 
    'IML', 
    'Gujarat Technological University', 
    'English', 
    'Chirag', 
    'https://drive.google.com/file/d/1q-gNkWKlszG1CEsmsXm6x07TwRdRjsxF/view?usp=sharing', 
    'pending', 
    '2024-10-10'
  ),
(
    '02715b73-acf3-4252-a029-ce8dd7e1ab8e', 
    'DSA IMP Algorithms', 
    'Most imp algorithms for basic concepts related to algorithms', 
    'Important Questions', 
    'BCA', 
    '-', 
    'DSA', 
    'Gujarat Technological University', 
    'English', 
    'Chirag', 
    'https://drive.google.com/file/d/1_ihNj7YoNzzdTrDnFJgchTLxURWvTXZt/view?usp=sharing', 
    'pending', 
    '2024-10-10'
  );
