// All materials from old E-Material website, mapped to GlobleCampus schema
// Fields: title, material_type, course, specialization, subject, university, language, description, uploaded_by, file_url, created_at

function mapType(t) {
  const m = {
    Paper: "Question Paper",
    "Paper Solution": "Question Paper",
    IMP: "Important Questions",
    Notes: "Notes",
    Assignment: "Assignment",
    "Lab Manual": "Lab Manual",
    Project: "Notes",
  };
  return m[t] || t;
}
function cleanSender(s) {
  return (
    (s || "").replace(/^sent[_ ]?by:?\s*/i, "").trim() || "GlobleCampus Team"
  );
}
function parseDate(d) {
  if (!d) return new Date().toISOString();
  const [day, month, year] = d.split("/");
  return new Date(`${year}-${month}-${day}T10:00:00Z`).toISOString();
}

const raw = [
  {
    link: "https://drive.google.com/file/d/1p8ZT1NszwraGUxFK93xlnL-SOcKQCjJV/view?usp=sharing",
    title: "Webtech Chapter 1 Network Basics Question Bank",
    course: "B.Tech",
    branch: "AI and Data Science",
    sub: "Introduction To Webtech",
    leng: "English",
    type: "Paper",
    desc: "Chapter 1 of intro to webtech question bank solution",
    clg: "JG University",
    sent_by: "Chirag Mahajan",
    date: "10/02/2026",
  },
  {
    link: "https://drive.google.com/file/d/1reFlK9KCuqFxufiokcq7UYK3rkCLB1Tk/view?usp=drive_link",
    title: "Mathematics-I Paper Solution",
    course: "BE",
    branch: "All",
    sub: "Mathematics-I",
    leng: "English",
    type: "Paper",
    desc: "Fully Paper Solution of Mathematics-I Monark Uni",
    clg: "Monark University",
    sent_by: "E-Material Team",
    date: "11/12/2025",
  },
  {
    link: "https://drive.google.com/file/d/1-uOfBYp_Ok7p65N1e54GtA4GhaoGcT3f/view?usp=sharing",
    title: "PTC University Paper",
    course: "BE",
    branch: "All",
    sub: "PTC",
    leng: "English",
    type: "Paper",
    desc: "PTC University Exam Paper Sem-3 Monark Uni Dec/25",
    clg: "Monark University",
    sent_by: "E-Material Team",
    date: "11/12/2025",
  },
  {
    link: "https://drive.google.com/file/d/1BCtJoAnnr9864kcKIYz-gY1S4svJXfYl/view?usp=sharing",
    title: "Probability & Statistics University Paper",
    course: "BE",
    branch: "All",
    sub: "Probability & Statistics",
    leng: "English",
    type: "Paper",
    desc: "Probability & Statistics University Exam Paper Sem-3 Monark Uni Dec/25",
    clg: "Monark University",
    sent_by: "E-Material Team",
    date: "11/12/2025",
  },
  {
    link: "https://drive.google.com/file/d/1Xx28qiqI7U-p_kmkBlTptXa7rG15jbIt/view?usp=sharing",
    title: "FDE University Paper",
    course: "BE",
    branch: "All",
    sub: "FDE",
    leng: "English",
    type: "Paper",
    desc: "FDE University Exam Paper Sem-3 Monark Uni Dec/25",
    clg: "Monark University",
    sent_by: "E-Material Team",
    date: "11/12/2025",
  },
  {
    link: "https://drive.google.com/file/d/1OPUWd9bWTBqP3uLCDIg60TRaSOP2Lb9Y/view?usp=sharing",
    title: "DBMS University Paper",
    course: "BE",
    branch: "All",
    sub: "DBMS",
    leng: "English",
    type: "Paper",
    desc: "DBMS University Exam Paper Sem-3 Monark Uni Dec/25",
    clg: "Monark University",
    sent_by: "E-Material Team",
    date: "11/12/2025",
  },
  {
    link: "https://drive.google.com/file/d/1ytMV8R1cwtgLjGTEyhp6y2rviQgvLS5o/view?usp=sharing",
    title: "ICSD University Paper",
    course: "BE",
    branch: "All",
    sub: "ICSD",
    leng: "English",
    type: "Paper",
    desc: "ICSD University Exam Paper Sem-3 Monark Uni Dec/25",
    clg: "Monark University",
    sent_by: "E-Material Team",
    date: "11/12/2025",
  },
  {
    link: "https://drive.google.com/file/d/1hNmy73R6TrlzApzIs77c7WL483rJGkDy/view?usp=sharing",
    title: "Data Structure University Paper",
    course: "BE",
    branch: "All",
    sub: "Data Structure",
    leng: "English",
    type: "Paper",
    desc: "Data Structure University Exam Paper Sem-3 Monark Uni Dec/25",
    clg: "Monark University",
    sent_by: "E-Material Team",
    date: "11/12/2025",
  },
  {
    link: "https://drive.google.com/file/d/1Yjkr6C6L52-HvZgPOVewcBDRSs7ZePp9/view?usp=sharing",
    title: "Indian Constitution University Paper",
    course: "BE",
    branch: "All",
    sub: "Indian Constitution",
    leng: "English",
    type: "Paper",
    desc: "Indian Constitution University Exam Paper Sem-3 Monark Uni Dec/25",
    clg: "Monark University",
    sent_by: "E-Material Team",
    date: "11/12/2025",
  },
  {
    link: "https://drive.google.com/file/d/1USRbCLJb9zjQpHwOdqxcf6ZEaPSj-kJN/view?usp=sharing",
    title: "Indian Constitution FAQ Answer Document",
    course: "BE",
    branch: "All",
    sub: "Indian Constitution",
    leng: "English",
    type: "IMP",
    desc: "Indian Constitution ALL FAQS With Answers",
    clg: "Monark University",
    sent_by: "Jiya",
    date: "30/11/2025",
  },
  {
    link: "https://drive.google.com/file/d/13rZnIkC8KLlsbwV2t4J5PIrfLVvG4ZUf/view?usp=sharing",
    title: "DBMS FAQ Handwritten Answer",
    course: "BE",
    branch: "Computer",
    sub: "DBMS",
    leng: "English",
    type: "IMP",
    desc: "DBMS ALL FAQS With Handwritten Answers",
    clg: "Monark University",
    sent_by: "Jiya",
    date: "27/11/2025",
  },
  {
    link: "https://drive.google.com/file/d/1YJ_Af0_ofHbNgtNsUdGOIcSNEepJbKl5/view?usp=sharing",
    title: "DBMS FAQ Answer Document",
    course: "BE",
    branch: "All",
    sub: "DBMS",
    leng: "English",
    type: "IMP",
    desc: "DBMS ALL FAQS With Answers",
    clg: "Monark University",
    sent_by: "Jiya",
    date: "27/11/2025",
  },
  {
    link: "https://drive.google.com/file/d/10XW-Hx74ba9umh9svpJaGmWl908KTgUr/view?usp=sharing",
    title: "DBMS FAQs for University Exam",
    course: "BE",
    branch: "All",
    sub: "DBMS",
    leng: "English",
    type: "IMP",
    desc: "DBMS ALL FAQS",
    clg: "Monark University",
    sent_by: "Poojan Desai",
    date: "27/11/2025",
  },
  {
    link: "https://drive.google.com/file/d/10BKl81M0gQq5dnIbTgM7iylHAwiZ7d_O/view?usp=sharing",
    title: "FDE FAQ Answer Document",
    course: "BE",
    branch: "All",
    sub: "FDE",
    leng: "English",
    type: "IMP",
    desc: "FDE ALL FAQS With Answers",
    clg: "Monark University",
    sent_by: "Jiya",
    date: "26/11/2025",
  },
  {
    link: "https://drive.google.com/file/d/1I3Oqjj1gdupA50kK_cP7Uv61mf52UVMv/view?usp=sharing",
    title: "DS FAQ Handwritten Answer",
    course: "BE",
    branch: "Computer",
    sub: "DS",
    leng: "English",
    type: "IMP",
    desc: "Data Structure ALL FAQS With Handwritten Answers",
    clg: "Monark University",
    sent_by: "Jiya",
    date: "22/11/2025",
  },
  {
    link: "https://drive.google.com/file/d/1r4ug4RCxeug_xetQiYLrg7CkkB6DL40Q/view?usp=sharing",
    title: "DS FAQ Answer Document",
    course: "BE",
    branch: "All",
    sub: "DS",
    leng: "English",
    type: "IMP",
    desc: "Data Structure ALL FAQS With Answers",
    clg: "Monark University",
    sent_by: "Jiya",
    date: "22/11/2025",
  },
  {
    link: "https://drive.google.com/file/d/1odeMjia0_FmzAotx0vCAKrYpk74opvGl/view?usp=sharing",
    title: "DS FAQs for University Exam",
    course: "BE",
    branch: "All",
    sub: "Data Structure",
    leng: "English",
    type: "IMP",
    desc: "DS ALL FAQS",
    clg: "Monark University",
    sent_by: "Monark University",
    date: "22/11/2025",
  },
  {
    link: "https://drive.google.com/file/d/1XVynxAsqWKkj8VZ6fferBQLtd-xgc7yZ/view?usp=sharing",
    title: "PTC FAQ Handwritten Answer",
    course: "BE",
    branch: "Computer",
    sub: "PTC",
    leng: "English",
    type: "IMP",
    desc: "PTC ALL FAQS With Handwritten Answers",
    clg: "Monark University",
    sent_by: "Jiya",
    date: "22/11/2025",
  },
  {
    link: "https://drive.google.com/file/d/1btviYeRx5oWNOTNai8Ciz-SuVoepUygO/view?usp=sharing",
    title: "PTC FAQ Answer Document",
    course: "BE",
    branch: "All",
    sub: "PTC",
    leng: "English",
    type: "IMP",
    desc: "PTC ALL FAQS With Answers",
    clg: "Monark University",
    sent_by: "Jiya",
    date: "22/11/2025",
  },
  {
    link: "https://drive.google.com/file/d/1VEo5MITMdoR5IFFexrmOiNBgqskYr-ER/view?usp=sharing",
    title: "PTC FAQs for University Exam",
    course: "BE",
    branch: "All",
    sub: "PTC",
    leng: "English",
    type: "IMP",
    desc: "PTC ALL FAQS",
    clg: "Monark University",
    sent_by: "Poojan Desai",
    date: "22/11/2025",
  },
  {
    link: "https://drive.google.com/file/d/1FL5J4Gogob8e8HDAlzDypkXepjK9ki7L/view?usp=sharing",
    title: "DS All Assignment (MU)",
    course: "BE",
    branch: "Computer",
    sub: "Data Structure",
    leng: "English",
    type: "Assignment",
    desc: "DS ALL CH Assignment With Answers",
    clg: "Monark University",
    sent_by: "E-Material Team",
    date: "13/09/2025",
  },
  {
    link: "https://drive.google.com/file/d/1hzBO1pvDG5KdwGVGmLH1bJqvutXn9NTS/view?usp=sharing",
    title: "DS Ch-1,2 Assignment (MU)",
    course: "BE",
    branch: "Computer",
    sub: "Data Structure",
    leng: "English",
    type: "Assignment",
    desc: "DS Ch-1,2 Assignment With Answers",
    clg: "Monark University",
    sent_by: "PRAJAPATI KUSH",
    date: "08/09/2025",
  },
  {
    link: "https://drive.google.com/file/d/1QUBpd1p0gsN1sQB4jTCSbM_0BZ4BEViQ/view?usp=sharing",
    title: "FDE All Assignment (MU)",
    course: "BE",
    branch: "Computer",
    sub: "FDE",
    leng: "English",
    type: "Assignment",
    desc: "FDE All Assignment With Answers",
    clg: "Monark University",
    sent_by: "E-Material Team",
    date: "03/09/2025",
  },
  {
    link: "https://drive.google.com/file/d/1U38YMnCGqyU72KYpJBl0sJ-SkTagUwX0/view?usp=sharing",
    title: "DBMS All Assignment (MU)",
    course: "BE",
    branch: "Computer",
    sub: "DBMS",
    leng: "English",
    type: "Assignment",
    desc: "DBMS All Assignment With Answers",
    clg: "Monark University",
    sent_by: "E-Material Team",
    date: "31/08/2025",
  },
  {
    link: "https://drive.google.com/file/d/1Ho6bDx8whjleh4Mc14kafk0nF8pGNl61/view?usp=sharing",
    title: "CN Lab Manual with answer",
    course: "Diploma",
    branch: "Computer",
    sub: "Computer Network",
    leng: "English",
    type: "Lab Manual",
    desc: "CN Lab Manual With Answers",
    clg: "",
    sent_by: "Amanat Malek",
    date: "23/08/2025",
  },
  {
    link: "https://drive.google.com/file/d/1Q7Ehqx_pJbD9txWfzdG4ELFAgw90YCjW/view?usp=sharing",
    title: "DBMS Full Syllabus Notes",
    course: "Degree",
    branch: "Computer",
    sub: "DBMS",
    leng: "English",
    type: "Notes",
    desc: "DBMS Full syllabus Notes for degree students",
    clg: "",
    sent_by: "E-Material",
    date: "05/08/2025",
  },
];

export const materials2 = [
  {
    link: "https://drive.google.com/file/d/1rwYQ-LJg5okwt99r4opeeKFruCJ45suT/view?usp=sharing",
    title: "Introduction to NO SQL Lab Manual With Answer",
    course: "Diploma",
    branch: "Computer",
    sub: "Introduction to NO SQL",
    leng: "English",
    type: "Lab Manual",
    desc: "Introduction to NO SQL (4360704) Lab manual With Answer",
    clg: "",
    sent_by: "E-Material",
    date: "29/04/2025",
  },
  {
    link: "https://drive.google.com/file/d/1BpI_7EDd2G9YHKcdh2NY6gQvO1gmqSus/view?usp=sharing",
    title: "Basic of Information Security Lab Manual With Answer",
    course: "Diploma",
    branch: "Computer",
    sub: "Basic of Information Security",
    leng: "English",
    type: "Lab Manual",
    desc: "Basic of Information Security (4360702) Lab manual With Answer",
    clg: "",
    sent_by: "E-Material",
    date: "26/04/2025",
  },
  {
    link: "https://drive.google.com/file/d/1BNoWnLNxhsmxMxvAukiH9Stp53vNL7gA/view?usp=sharing",
    title: "DDCET Paper Solution 2024",
    course: "Diploma",
    branch: "Computer",
    sub: "DDCET",
    leng: "English",
    type: "Paper",
    desc: "DDCET Paper Solution 2024 last year",
    clg: "",
    sent_by: "E-Material",
    date: "09/04/2025",
  },
  {
    link: "https://drive.google.com/file/d/1b-zNFl4gKiPFcEfJPh5ooyeQzoaSPti8/view?usp=sharing",
    title: "Cloud Computing Lab Manual With Answer",
    course: "Diploma",
    branch: "Computer",
    sub: "Cloud Computing",
    leng: "English",
    type: "Lab Manual",
    desc: "Cloud Computing (4360709) Lab manual With Answer",
    clg: "",
    sent_by: "E-Material",
    date: "27/03/2025",
  },
  {
    link: "https://drive.google.com/file/d/1pxTAiHv3I4QRLEW5nl_ZA7e2QFJX2vdW/view?usp=sharing",
    title: "Computer Maintenance and Troubleshooting Lab Manual With Answer",
    course: "Diploma",
    branch: "Computer",
    sub: "Computer Maintenance and Troubleshooting",
    leng: "English",
    type: "Lab Manual",
    desc: "Computer Maintenance and Troubleshooting (4360701) Lab manual With Answer",
    clg: "",
    sent_by: "E-Material",
    date: "25/03/2025",
  },
  {
    link: "https://drive.google.com/file/d/1hKndL-Iy10WPeC8CAzVCFqTakNK82EO2/view?usp=sharing",
    title: "Computer Maintenance and Troubleshooting Assignment 1 to 3",
    course: "Diploma",
    branch: "Computer",
    sub: "Computer Maintenance and Troubleshooting",
    leng: "English",
    type: "Assignment",
    desc: "Sem 6 Computer Maintenance and Troubleshooting Unit 1 to 3 Handwritten Assignment",
    clg: "",
    sent_by: "E-Material",
    date: "23/03/2025",
  },
  {
    link: "https://drive.google.com/file/d/1sjcf0NtmYpk5tCvVnU-TK333BGN2og5j/view?usp=sharing",
    title: "Fundamentals Of IOT All Assignment",
    course: "Diploma",
    branch: "Computer",
    sub: "Fundamentals Of IOT",
    leng: "English",
    type: "Assignment",
    desc: "Sem 6 Fundamentals Of IOT All Units Handwritten Assignment",
    clg: "",
    sent_by: "E-Material",
    date: "21/03/2025",
  },
  {
    link: "https://drive.google.com/file/d/11BTsHBatAk7--1zp9c0dOWm7cWDmdWsR/view?usp=sharing",
    title: "BIS All Assignment",
    course: "Diploma",
    branch: "Computer",
    sub: "Basic of Information Security",
    leng: "English",
    type: "Assignment",
    desc: "Sem 6 BIS All Units Handwritten Assignment",
    clg: "",
    sent_by: "E-Material",
    date: "21/03/2025",
  },
  {
    link: "https://drive.google.com/file/d/1Yvn7xUCtBel16bqbiql2xoRunkybj-gw/view?usp=sharing",
    title: "Cloud Computing All Assignments",
    course: "Diploma",
    branch: "Computer",
    sub: "Cloud Computing",
    leng: "English",
    type: "Assignment",
    desc: "Sem 6 Cloud Computing All Assignments",
    clg: "",
    sent_by: "E-Material",
    date: "28/01/2025",
  },
  {
    link: "https://drive.google.com/file/d/1dMdWk4uY1dZHZyjaoCQy2QY5tU1rzNZ0/view?usp=sharing",
    title: "Cyber Security and Digital Forensics Lab Manual",
    course: "Diploma",
    branch: "IT",
    sub: "Cyber Security and Digital Forensics",
    leng: "English",
    type: "Lab Manual",
    desc: "Cyber Security and Digital Forensics Lab manual from GTU",
    clg: "GTU",
    sent_by: "E-Material",
    date: "22/01/2025",
  },
  {
    link: "https://drive.google.com/file/d/14b5xQvPxI4auXto9COBAUK_X4iBJ0_Ok/view?usp=sharing",
    title: "Cloud and Data Center Technologies Lab Manual",
    course: "Diploma",
    branch: "IT",
    sub: "Cloud and Data Center Technologies",
    leng: "English",
    type: "Lab Manual",
    desc: "Cloud and Data Center Technologies Lab manual from GTU",
    clg: "GTU",
    sent_by: "E-Material",
    date: "22/01/2025",
  },
  {
    link: "https://drive.google.com/file/d/1dgqb3qSgRcCiWN14fHKl4HXkfGve4M58/view?usp=sharing",
    title: "Fundamentals of IoT Lab Manual With Answer",
    course: "Diploma",
    branch: "Computer",
    sub: "Fundamentals of IoT",
    leng: "English",
    type: "Lab Manual",
    desc: "Fundamentals of IoT Lab manual With Answer",
    clg: "",
    sent_by: "E-Material",
    date: "17/01/2025",
  },
  {
    link: "https://drive.google.com/file/d/128C3bFcVZWhJ3NRapSzqXy72q61YNpzJ/view?usp=sharing",
    title: "Fundamentals of IoT Lab Manual",
    course: "Diploma",
    branch: "Computer",
    sub: "Fundamentals of IoT",
    leng: "English",
    type: "Lab Manual",
    desc: "Fundamentals of IoT Lab manual from GTU",
    clg: "GTU",
    sent_by: "E-Material",
    date: "17/01/2025",
  },
  {
    link: "https://drive.google.com/file/d/1570ZUss8mXpXtFrkEjavciMq2XufA9Eq/view?usp=sharing",
    title: "Cloud Computing Lab Manual",
    course: "Diploma",
    branch: "Computer",
    sub: "Cloud Computing",
    leng: "English",
    type: "Lab Manual",
    desc: "Cloud Computing Lab manual from GTU",
    clg: "GTU",
    sent_by: "E-Material",
    date: "17/01/2025",
  },
  {
    link: "https://drive.google.com/file/d/1TDFaBeyfuhsnnKqS_TvWgH2hf9fcp5r7/view?usp=sharing",
    title: "INS Lab Manual",
    course: "Diploma",
    branch: "Computer",
    sub: "Introduction to NO SQL",
    leng: "English",
    type: "Lab Manual",
    desc: "INS Lab manual from GTU",
    clg: "GTU",
    sent_by: "E-Material",
    date: "17/01/2025",
  },
  {
    link: "https://drive.google.com/file/d/1yXsUanjxCZxJYh2FAeQj-tuvxGVlhYHM/view?usp=sharing",
    title: "BIS Lab Manual",
    course: "Diploma",
    branch: "Computer",
    sub: "Basics of Information Security",
    leng: "English",
    type: "Lab Manual",
    desc: "BIS Lab manual from GTU",
    clg: "GTU",
    sent_by: "E-Material",
    date: "17/01/2025",
  },
  {
    link: "https://drive.google.com/file/d/1-fyoTwiUWzYx0_GUGqIUAG4axLX26QSo/view?usp=sharing",
    title: "CMTS Lab Manual",
    course: "Diploma",
    branch: "Computer",
    sub: "Computer Maintenance and Troubleshooting",
    leng: "English",
    type: "Lab Manual",
    desc: "CMTS Lab manual from GTU",
    clg: "GTU",
    sent_by: "E-Material",
    date: "17/01/2025",
  },
  {
    link: "https://drive.google.com/file/d/1-eo4jppkQqhRyNVXv6b_uirNGwokhzPg/view?usp=sharing",
    title: "Computer Networking Lab Manual",
    course: "Diploma",
    branch: "Computer",
    sub: "Computer Networking",
    leng: "English",
    type: "Lab Manual",
    desc: "Computer Networking Lab manual from GTU",
    clg: "GTU",
    sent_by: "E-Material",
    date: "17/01/2025",
  },
  {
    link: "https://drive.google.com/file/d/1s8IcbTvbe_WkA5LWcF_SsHu-IbReVLa0/view?usp=sharing",
    title: "JAVA Notes",
    course: "Computer Science",
    branch: "-",
    sub: "Coding",
    leng: "English",
    type: "Notes",
    desc: "IMP Notes for JAVA by Krish Wagh",
    clg: "",
    sent_by: "Krish Wagh",
    date: "16/01/2025",
  },
  {
    link: "https://drive.google.com/file/d/1Jo7EYiqKTOP2t4Y3Q2mgsY8EsiA6-Ky2/view?usp=sharing",
    title: "PHP Notes",
    course: "Computer Science",
    branch: "-",
    sub: "Coding",
    leng: "English",
    type: "Notes",
    desc: "IMP Notes for PHP by Devji",
    clg: "",
    sent_by: "Devji",
    date: "06/01/2025",
  },
  {
    link: "https://drive.google.com/file/d/13kV17UnY7hbK20kP2Drh6s60xOUZzwbr/view?usp=sharing",
    title: "Javascript Notes",
    course: "Computer Science",
    branch: "-",
    sub: "Coding",
    leng: "English",
    type: "Notes",
    desc: "IMP Notes for Javascript by Devji",
    clg: "",
    sent_by: "Devji",
    date: "01/01/2025",
  },
  {
    link: "https://drive.google.com/file/d/1uqnpKmwrADgmJYXyL8EWJ2BayLelJ2ZW/view?usp=sharing",
    title: "CSS Notes",
    course: "Computer Science",
    branch: "-",
    sub: "Coding",
    leng: "English",
    type: "Notes",
    desc: "IMP Notes for CSS by Devji",
    clg: "",
    sent_by: "Devji",
    date: "01/01/2025",
  },
  {
    link: "https://drive.google.com/file/d/1Uey5DXx5PiwLI0mysIgvd81uokk93Wzg/view?usp=sharing",
    title: "HTML Notes",
    course: "Computer Science",
    branch: "-",
    sub: "Coding",
    leng: "English",
    type: "Notes",
    desc: "IMP Notes for HTML by Devji",
    clg: "",
    sent_by: "Devji",
    date: "01/01/2025",
  },
  {
    link: "https://drive.google.com/drive/folders/1RB5t3Xt8dtoRdBMubBQQTN-fISNv687b",
    title: "C Programming Notes",
    course: "Computer Science",
    branch: "-",
    sub: "Coding",
    leng: "English",
    type: "Notes",
    desc: "IMP Notes for C Programming by Devji",
    clg: "",
    sent_by: "Devji",
    date: "30/12/2024",
  },
  {
    link: "https://drive.google.com/file/d/1t0qGOTV2_1O4oM7UJ3JLrYTJyO71UmOG/view?usp=sharing",
    title: "Quantum Computing Notes",
    course: "Computer Science",
    branch: "-",
    sub: "Coding",
    leng: "English",
    type: "Notes",
    desc: "IMP Notes for Quantum Computing by Devji",
    clg: "",
    sent_by: "Devji",
    date: "30/12/2024",
  },
  {
    link: "https://drive.google.com/file/d/14Ru7qUuZEbNnpBX-N8lulWLxs9iyTJfd/view?usp=sharing",
    title: "Python Notes",
    course: "Computer Science",
    branch: "-",
    sub: "Coding",
    leng: "English",
    type: "Notes",
    desc: "IMP Notes for Python by Devji",
    clg: "",
    sent_by: "Devji",
    date: "30/12/2024",
  },
  {
    link: "https://drive.google.com/file/d/1TnLXta0tC2WNkkItiRaYnsHpmmlrPw8r/view?usp=sharing",
    title: "Java Notes",
    course: "Computer Science",
    branch: "-",
    sub: "Coding",
    leng: "English",
    type: "Notes",
    desc: "IMP Notes for Java by Devji",
    clg: "",
    sent_by: "Devji",
    date: "28/12/2024",
  },
  {
    link: "https://drive.google.com/file/d/1BUmgJmU4Q5oRzOmcnXUHFAzGkheOzxpl/view?usp=sharing",
    title: "C++ Notes",
    course: "Computer Science",
    branch: "-",
    sub: "Coding",
    leng: "English",
    type: "Notes",
    desc: "IMP Notes for C++ by Devji",
    clg: "",
    sent_by: "Devji",
    date: "30/12/2024",
  },
];

export const materials3 = [
  {
    link: "https://drive.google.com/file/d/1vLUEbyeu6x4Vir-5sLoYvg0vs3UIy7sk/view?usp=sharing",
    title: "Most IMP questions for ACN",
    course: "Diploma",
    branch: "Computer",
    sub: "Advance Computer Network",
    leng: "English",
    type: "IMP",
    desc: "Most imp questions for ACN subject",
    clg: "",
    sent_by: "Chirag",
    date: "23/11/2024",
  },
  {
    link: "https://drive.google.com/file/d/1kiyTb0j0IAV8SgE4bxEHayouH4yAYkxl/view?usp=sharing",
    title: "COA IMP GTU PAPER",
    course: "Diploma",
    branch: "Computer",
    sub: "Computer Organisations and Architecture",
    leng: "English",
    type: "Paper",
    desc: "COA GTU IMP Question and Answers",
    clg: "GTU",
    sent_by: "Chirag",
    date: "12/11/2024",
  },
  {
    link: "https://drive.google.com/file/d/1MBLNYJmDPajiiPcYIf3pu0rspM15HaxN/view?usp=drive_link",
    title: "AOOP GTU PAPER (S-2024)",
    course: "Diploma",
    branch: "Computer",
    sub: "Advance Object Oriented Programming",
    leng: "English",
    type: "Paper",
    desc: "AOOP GTU PAPER Summer 2024",
    clg: "GTU",
    sent_by: "Harshil",
    date: "12/11/2024",
  },
  {
    link: "https://drive.google.com/file/d/1nR3kmbq5dagWzjIeF5iAt19HYzvI7ke6/view?usp=drive_link",
    title: "CN GTU PAPER (S-2024)",
    course: "Diploma",
    branch: "Computer",
    sub: "Computer Network",
    leng: "English",
    type: "Paper",
    desc: "Computer Network GTU PAPER Summer 2024",
    clg: "GTU",
    sent_by: "Harshil",
    date: "12/11/2024",
  },
  {
    link: "https://drive.google.com/file/d/1l_ofYxNyhyIMvKK7WBAoBL2socvDEcfX/view?usp=drive_link",
    title: "ISE GTU PAPER (S-2024)",
    course: "Diploma",
    branch: "Computer",
    sub: "Introduction to Software Engineering",
    leng: "English",
    type: "Paper",
    desc: "ISE GTU PAPER Summer 2024",
    clg: "GTU",
    sent_by: "Harshil",
    date: "12/11/2024",
  },
  {
    link: "https://drive.google.com/file/d/1tZLRotMk1NtRAl6kzjJjUsao3MA5oqJ4/view?usp=drive_link",
    title: "IWD GTU PAPER (S-2024)",
    course: "Diploma",
    branch: "Computer",
    sub: "Introduction to Web Development",
    leng: "English",
    type: "Paper",
    desc: "IWD GTU PAPER Summer 2024",
    clg: "GTU",
    sent_by: "Harshil",
    date: "12/11/2024",
  },
  {
    link: "https://drive.google.com/file/d/1jXXBleSP4f1xa-TQlCxDajUFk-pIBCZW/view?usp=drive_link",
    title: "DSA GTU PAPER (S-2024)",
    course: "Diploma",
    branch: "Computer",
    sub: "Data Structure and Algorithms",
    leng: "English",
    type: "Paper",
    desc: "DSA GTU PAPER Summer 2024",
    clg: "GTU",
    sent_by: "Harshil",
    date: "12/11/2024",
  },
  {
    link: "https://drive.google.com/file/d/1_nt9mhqZGlllGtnzjBeyZs9FlhU0B5yK/view?usp=sharing",
    title: "RDBMS GTU PAPER (S-2024)",
    course: "Diploma",
    branch: "Computer",
    sub: "Relational Database Management System",
    leng: "English",
    type: "Paper",
    desc: "RDBMS GTU PAPER Summer 2024",
    clg: "GTU",
    sent_by: "Harshil",
    date: "12/11/2024",
  },
  {
    link: "https://drive.google.com/file/d/1A-xSsS0LIpOgbSAbX2gMdeRp--xoWees/view?usp=drive_link",
    title: "BOS GTU PAPER (S-2024)",
    course: "Diploma",
    branch: "Computer",
    sub: "Basics of Operating System",
    leng: "English",
    type: "Paper",
    desc: "BOS GTU PAPER Summer 2024",
    clg: "GTU",
    sent_by: "Harshil",
    date: "12/11/2024",
  },
  {
    link: "https://drive.google.com/file/d/1VGOGCems8h_NxCH5Tc9ylnoC2iSxFXCk/view?usp=sharing",
    title: "BDE GTU PAPER (S-2024)",
    course: "Diploma",
    branch: "Computer",
    sub: "Basics of Digital Electronics",
    leng: "English",
    type: "Paper",
    desc: "BDE GTU PAPER Summer 2024",
    clg: "GTU",
    sent_by: "Harshil",
    date: "12/11/2024",
  },
  {
    link: "https://drive.google.com/file/d/1HjjbQ7cdycKJGJc8O7_LjdczrA5BiL_l/view?usp=drive_link",
    title: "Engineering Mathematics GTU PAPER (S-2024)",
    course: "Diploma",
    branch: "Computer",
    sub: "Engineering Mathematics",
    leng: "English",
    type: "Paper",
    desc: "Engineering Mathematics GTU PAPER Summer 2024",
    clg: "GTU",
    sent_by: "Harshil",
    date: "12/11/2024",
  },
  {
    link: "https://drive.google.com/file/d/1QE-72N-liipTPwjAJB8SeJFBUEKoRA1C/view?usp=sharing",
    title: "COA Lab Manual With Answer",
    course: "Diploma",
    branch: "Computer",
    sub: "COA",
    leng: "English",
    type: "Lab Manual",
    desc: "COA Lab Manual With Answer",
    clg: "GTU",
    sent_by: "Harshil",
    date: "21/10/2024",
  },
  {
    link: "https://drive.google.com/file/d/1SE4WCWpxw7EkHJyiL5lMqwu_4uiN9B3-/view?usp=sharing",
    title: "ACN Lab Manual With Answer",
    course: "Diploma",
    branch: "Computer",
    sub: "ACN",
    leng: "English",
    type: "Lab Manual",
    desc: "ACN Lab Manual With Answer",
    clg: "GTU",
    sent_by: "Harshil",
    date: "20/10/2024",
  },
  {
    link: "https://drive.google.com/file/d/11GDJkCDadCYT4DqrUERNbRIV1Iej5Ja7/view?usp=sharing",
    title: "IML Lab Manual With Answer",
    course: "Diploma",
    branch: "Computer",
    sub: "IML",
    leng: "English",
    type: "Lab Manual",
    desc: "IML Lab Manual With Answer",
    clg: "GTU",
    sent_by: "Mufiz",
    date: "20/10/2024",
  },
  {
    link: "https://drive.google.com/file/d/15edcY4wbBDCrpux6nU1XxuMcyecL_ydZ/view?usp=sharing",
    title: "ACN Lab Manual (GTU)",
    course: "Diploma",
    branch: "Computer",
    sub: "ACN",
    leng: "English",
    type: "Lab Manual",
    desc: "ACN Lab manual from GTU",
    clg: "GTU",
    sent_by: "Harshil",
    date: "20/10/2024",
  },
  {
    link: "https://drive.google.com/file/d/1_95cVuImF1LGvW2iGXIKexpeJKIubtYS/view?usp=sharing",
    title: "IML Lab Manual (GTU)",
    course: "Diploma",
    branch: "Computer",
    sub: "IML",
    leng: "English",
    type: "Lab Manual",
    desc: "IML Lab manual from GTU",
    clg: "GTU",
    sent_by: "Harshil",
    date: "20/10/2024",
  },
  {
    link: "https://drive.google.com/file/d/1I7nBPVXtxq4HrT1do6NHlfYMX0eOmadr/view?usp=sharing",
    title: "COA Lab Manual (GTU)",
    course: "Diploma",
    branch: "Computer",
    sub: "COA",
    leng: "English",
    type: "Lab Manual",
    desc: "COA Lab manual from GTU",
    clg: "GTU",
    sent_by: "Harshil",
    date: "20/10/2024",
  },
  {
    link: "https://drive.google.com/file/d/1rt5sGDIBlEpQiPP9tE7-vXYCFlXcdFxk/view?usp=sharing",
    title: "ACN Assignment All",
    course: "Diploma",
    branch: "Computer",
    sub: "ACN",
    leng: "English",
    type: "Assignment",
    desc: "Sem 5 ACN All Chapter Handwritten Assignment",
    clg: "",
    sent_by: "Chirag",
    date: "18/10/2024",
  },
  {
    link: "https://drive.google.com/file/d/1kiyTb0j0IAV8SgE4bxEHayouH4yAYkxl/view?usp=sharing",
    title: "COA Assignment All",
    course: "Diploma",
    branch: "Computer",
    sub: "COA",
    leng: "English",
    type: "Assignment",
    desc: "Sem 5 COA All Chapter Handwritten Assignment",
    clg: "",
    sent_by: "Chirag",
    date: "15/10/2024",
  },
  {
    link: "https://drive.google.com/file/d/1NGyFToJ-uzw2JS3k6TgztJ1g_wE16dyV/view?usp=sharing",
    title: "Financial Accounting Assignment 2",
    course: "B.Com",
    branch: "-",
    sub: "Financial Accounting",
    leng: "Gujarati",
    type: "Assignment",
    desc: "Second handwritten assignment of financial accounting b.com 1st sem",
    clg: "",
    sent_by: "Man Panchal",
    date: "11/10/2024",
  },
  {
    link: "https://drive.google.com/file/d/1ztyDv41R7I7Aa2T852TDig_mu2qvFjyy/view?usp=sharing",
    title: "Marketing Management Notes",
    course: "B.Com",
    branch: "-",
    sub: "Marketing Management",
    leng: "Gujarati",
    type: "Notes",
    desc: "Handwritten notes for marketing management b.com 1st sem",
    clg: "",
    sent_by: "Man Panchal",
    date: "11/10/2024",
  },
  {
    link: "https://drive.google.com/file/d/1PvFWvnUe5GHDVsHhVtv_9RCdaAxQuSOS/view?usp=sharing",
    title: "Economics Notes",
    course: "B.Com",
    branch: "-",
    sub: "Economics",
    leng: "Gujarati",
    type: "Notes",
    desc: "Handwritten notes for b.com 1st sem economics",
    clg: "",
    sent_by: "Man Panchal",
    date: "11/10/2024",
  },
  {
    link: "https://drive.google.com/file/d/1MdYSmqPiGuoaef7mprZwc59YsW5eu3nA/view?usp=sharing",
    title: "Indian Knowledge System Notes",
    course: "B.Com",
    branch: "-",
    sub: "Indian Knowledge System",
    leng: "Gujarati",
    type: "Notes",
    desc: "Handwritten notes of IKS b.com 1st sem",
    clg: "",
    sent_by: "Man Panchal",
    date: "11/10/2024",
  },
  {
    link: "https://drive.google.com/file/d/1HIeWnuF64M0ZeZ4vt4GrPh5cBYm_osnp/view?usp=sharing",
    title: "Financial Accounting Assignment 1",
    course: "B.Com",
    branch: "-",
    sub: "Financial Accounting",
    leng: "Gujarati",
    type: "Assignment",
    desc: "Handwritten assignment 1 of Financial Accounting b.com 1st sem",
    clg: "",
    sent_by: "Man Panchal",
    date: "11/10/2024",
  },
  {
    link: "https://drive.google.com/file/d/1q-gNkWKlszG1CEsmsXm6x07TwRdRjsxF/view?usp=sharing",
    title: "IML Assignment All",
    course: "Diploma",
    branch: "Computer",
    sub: "IML",
    leng: "English",
    type: "Assignment",
    desc: "Diploma Computer Sem 5 IML All Chapter Handwritten Assignment",
    clg: "",
    sent_by: "Chirag",
    date: "10/10/2024",
  },
  {
    link: "https://drive.google.com/file/d/1_ihNj7YoNzzdTrDnFJgchTLxURWvTXZt/view?usp=sharing",
    title: "DSA IMP Algorithms",
    course: "BCA",
    branch: "-",
    sub: "DSA",
    leng: "English",
    type: "IMP",
    desc: "Most imp algorithms for basic concepts related to algorithms",
    clg: "",
    sent_by: "Chirag",
    date: "10/10/2024",
  },
];

export const materials4 = [
  {
    link: "https://drive.google.com/file/d/1ydSLtgqV_Aa9bo87DjalH-4Krb8FVG4e/view?usp=drive_link",
    title: "AOOP Labmanual",
    course: "Diploma",
    branch: "Computer",
    sub: "AOOP",
    leng: "English",
    type: "Lab Manual",
    desc: "AOOP Labmanual from GTU",
    clg: "GTU",
    sent_by: "Harshil",
    date: "01/07/2024",
  },
  {
    link: "https://drive.google.com/file/d/1ooHqCaspmF7b3c1i-kyHjU_ZVPQHbAQZ/view?usp=drive_link",
    title: "CN Labmanual",
    course: "Diploma",
    branch: "Computer",
    sub: "CN",
    leng: "English",
    type: "Lab Manual",
    desc: "CN Labmanual from GTU",
    clg: "GTU",
    sent_by: "Harshil",
    date: "01/07/2024",
  },
  {
    link: "https://drive.google.com/file/d/1cFlLgd_aqO1-8Eii1cXuxpqBzdeJVF-k/view?usp=drive_link",
    title: "IWD Labmanual",
    course: "Diploma",
    branch: "Computer",
    sub: "IWD",
    leng: "English",
    type: "Lab Manual",
    desc: "IWD Labmanual from GTU",
    clg: "GTU",
    sent_by: "Harshil",
    date: "01/07/2024",
  },
  {
    link: "https://drive.google.com/file/d/1-k63z5U2_vzQR5-0jOl-GVBILTl6YqPg/view?usp=drive_link",
    title: "ISE Labmanual",
    course: "Diploma",
    branch: "Computer",
    sub: "ISE",
    leng: "English",
    type: "Lab Manual",
    desc: "ISE Labmanual from GTU",
    clg: "GTU",
    sent_by: "Harshil",
    date: "03/07/2024",
  },
  {
    link: "https://drive.google.com/file/d/1fm4FOuqW0naVVDRq2GACzvuRqDAf6hss/view?usp=drive_link",
    title: "ISE Labmanual Answer",
    course: "Diploma",
    branch: "Computer",
    sub: "ISE",
    leng: "English",
    type: "Lab Manual",
    desc: "ISE Labmanual With Answer",
    clg: "GTU",
    sent_by: "Harshil",
    date: "03/07/2024",
  },
  {
    link: "https://drive.google.com/file/d/1tTCGWw_CLKPYcocWl5I4vHmVc70YAn6U/view?usp=drive_link",
    title: "IWD Labmanual Answer",
    course: "Diploma",
    branch: "Computer",
    sub: "IWD",
    leng: "English",
    type: "Lab Manual",
    desc: "IWD Labmanual With Answer",
    clg: "GTU",
    sent_by: "Harshil",
    date: "03/07/2024",
  },
  {
    link: "https://drive.google.com/file/d/1ATZpolpmGhEKOSQzOpgerVIh8o6VYX2l/view?usp=drive_link",
    title: "CN Labmanual Answer",
    course: "Diploma",
    branch: "Computer",
    sub: "CN",
    leng: "English",
    type: "Lab Manual",
    desc: "CN Labmanual With Answer",
    clg: "GTU",
    sent_by: "Harshil",
    date: "03/07/2024",
  },
  {
    link: "https://drive.google.com/file/d/1MueIWOdbclc0TEL9Wf6bL6YVTfHzilId/view?usp=drive_link",
    title: "AOOP Labmanual Answer",
    course: "Diploma",
    branch: "Computer",
    sub: "AOOP",
    leng: "English",
    type: "Lab Manual",
    desc: "AOOP Labmanual With Answer",
    clg: "GTU",
    sent_by: "Harshil",
    date: "03/07/2024",
  },
  {
    link: "https://drive.google.com/file/d/16Btq5xmgQYjylTsSu8R01-fyima-wTsZ/view?usp=drive_link",
    title: "BOOP GTU PAPER (S-2022)",
    course: "Diploma",
    branch: "Computer",
    sub: "BOOP",
    leng: "English",
    type: "Paper",
    desc: "BOOP GTU PAPER Summer 2022",
    clg: "GTU",
    sent_by: "Harshil",
    date: "03/07/2024",
  },
  {
    link: "https://drive.google.com/file/d/1WAxlNscqI1TpFq9arsEQ6hJRresnj3zJ/view?usp=drive_link",
    title: "BOOP GTU PAPER (W-2022)",
    course: "Diploma",
    branch: "Computer",
    sub: "BOOP",
    leng: "English",
    type: "Paper",
    desc: "BOOP GTU PAPER Winter 2022",
    clg: "GTU",
    sent_by: "Harshil",
    date: "03/07/2024",
  },
  {
    link: "https://drive.google.com/file/d/1k79oROaeSf-H73Csm8UR8ycOXECvfLYV/view?usp=sharing",
    title: "BCP GTU PAPER (2022)",
    course: "Diploma",
    branch: "Computer",
    sub: "BCP",
    leng: "English",
    type: "Paper",
    desc: "BCP GTU PAPER 2022",
    clg: "GTU",
    sent_by: "Harshil",
    date: "10/07/2024",
  },
  {
    link: "https://drive.google.com/file/d/1DkZDvu2sdMwHxrcQUwUbe3hpevxgrvA4/view?usp=sharing",
    title: "BDE GTU PAPER (2022)",
    course: "Diploma",
    branch: "Computer",
    sub: "BDE",
    leng: "English",
    type: "Paper",
    desc: "BDE GTU PAPER 2022",
    clg: "GTU",
    sent_by: "Harshil",
    date: "10/07/2024",
  },
  {
    link: "https://drive.google.com/file/d/16l5SwHiYIf3g3m9VN0W_bt4NvphacODr/view?usp=sharing",
    title: "Basic SQL Course",
    course: "Computer Science",
    branch: "-",
    sub: "DBMS or RDBMS",
    leng: "English",
    type: "Notes",
    desc: "Basic all concepts for SQL Language with code",
    clg: "",
    sent_by: "Harshil",
    date: "01/07/2024",
  },
  {
    link: "https://drive.google.com/file/d/1mmHFAPABA89D-Jo6yDIuFAEgdpF_-kuP/view?usp=sharing",
    title: "Basic Python Course",
    course: "Computer Science",
    branch: "-",
    sub: "Python Programming",
    leng: "English",
    type: "Notes",
    desc: "Basic all concepts for Python Language with code",
    clg: "",
    sent_by: "Harshil",
    date: "01/07/2024",
  },
  {
    link: "https://drive.google.com/file/d/17w4fQlNac_hwsJWtoPDZjJq6a-JZG5Au/view?usp=sharing",
    title: "Emerging Computer Technologies",
    course: "BCA",
    branch: "-",
    sub: "Emerging Computer Technologies",
    leng: "English",
    type: "Notes",
    desc: "Today's technology input, output and digital storage unit 1",
    clg: "",
    sent_by: "Zala Manav",
    date: "01/07/2024",
  },
  {
    link: "https://1drv.ms/p/c/25bd291b995dd854/EVTYXZkbKb0ggCUlFgAAAAAB8V4GhbLuzetHn4v0TtgqfA",
    title: "Book Review (Rich Dad Poor Dad)",
    course: "Diploma",
    branch: "Computer",
    sub: "CPD",
    leng: "English",
    type: "Notes",
    desc: "PPT Book Review with brief detail and main points",
    clg: "",
    sent_by: "Harshil",
    date: "01/07/2024",
  },
  {
    link: "https://drive.google.com/file/d/1FIVTH5o3lnmdSb911r9UcZNDvXWAjoy9/view",
    title: "Marketing Management in Practice (5013)",
    course: "B.Com",
    branch: "-",
    sub: "MMIP",
    leng: "English",
    type: "Notes",
    desc: "Marketing Management in Practice (5013) Notes",
    clg: "",
    sent_by: "Chirag",
    date: "15/08/2024",
  },
  {
    link: "https://drive.google.com/file/d/1uR-V9o_1p_isWqs1YywbY20uz-CgDh0m/view",
    title: "Statistics (5013)",
    course: "B.Com",
    branch: "-",
    sub: "Statistics",
    leng: "English",
    type: "Notes",
    desc: "Statistics (5013) Notes",
    clg: "",
    sent_by: "Chirag",
    date: "15/08/2024",
  },
  {
    link: "https://drive.google.com/file/d/1oeE1rFjcf0Ak4ZqaET5S5GLBq8ZUqAeW/view",
    title: "Management Accountancy",
    course: "B.Com",
    branch: "-",
    sub: "Management Accountancy",
    leng: "English",
    type: "Notes",
    desc: "Management Accountancy Notes",
    clg: "",
    sent_by: "Chirag",
    date: "15/08/2024",
  },
  {
    link: "https://drive.google.com/file/d/1ljyuBGzUysOGXZWVD7189GyhbEse-wKD/view",
    title: "Business Law",
    course: "B.Com",
    branch: "-",
    sub: "Business Law",
    leng: "English",
    type: "Notes",
    desc: "Business Law Notes",
    clg: "",
    sent_by: "Chirag",
    date: "15/08/2024",
  },
  {
    link: "https://drive.google.com/file/d/1katH4C1stv3wtqSg7QYktWxJUmE4FMiM/view",
    title: "Commercial Communication",
    course: "B.Com",
    branch: "-",
    sub: "Commercial Communication",
    leng: "English",
    type: "Notes",
    desc: "Commercial Communication Notes",
    clg: "",
    sent_by: "Chirag",
    date: "28/08/2024",
  },
  {
    link: "https://drive.google.com/file/d/1RCDaSF8rfQvzVcGudrWJkOsi_Q-q0oUN/view",
    title: "Cost Accounting",
    course: "B.Com",
    branch: "-",
    sub: "Cost Accounting",
    leng: "English",
    type: "Notes",
    desc: "Cost Accounting Notes",
    clg: "",
    sent_by: "Chirag",
    date: "28/08/2024",
  },
  {
    link: "https://drive.google.com/file/d/1PTxlGNwHQSSn-qEzTwRGeeQuaIdfJiTg/view",
    title: "Indian Economy",
    course: "B.Com",
    branch: "-",
    sub: "Indian Economy",
    leng: "English",
    type: "Notes",
    desc: "Indian Economy Notes",
    clg: "",
    sent_by: "Chirag",
    date: "28/08/2024",
  },
];

export function getAllMaterials() {
  const all = [...raw, ...materials2, ...materials3, ...materials4];
  return all.map((m) => ({
    title: m.title || "Untitled",
    material_type: mapType(m.type),
    course: m.course || "",
    specialization:
      m.branch === "-" ||
      m.branch === "ALL" ||
      m.branch === "All" ||
      m.branch === "ALl"
        ? "All"
        : m.branch || "All",
    subject: (m.sub || "").trim(),
    university: m.clg || "",
    language: m.leng || "English",
    description: (m.desc || "").replace(/^"|"$/g, "").trim(),
    uploaded_by: cleanSender(m.sent_by),
    file_url: m.link,
    status: "approved",
    created_at: parseDate(m.date),
  }));
}
